CREATE TABLE "funcionario" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"empresa_id" INTEGER NOT NULL,
	"funcao_id" INTEGER NOT NULL,
	"nome" VARCHAR(100) NOT NULL,
	"sobrenome" VARCHAR(100),
	"status" VARCHAR(20) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"data_contratacao" DATE,
	PRIMARY KEY("id")
);

ALTER TABLE "funcionario"
ADD FOREIGN KEY("empresa_id") REFERENCES "empresa"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "funcionario"												
ADD FOREIGN KEY("funcao_id") REFERENCES "funcao"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;