CREATE TABLE "item_pedido" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"produto_id" INTEGER,
	"pedido_id" INTEGER,
	"quantidade" INTEGER,
	"preco_unitario" DECIMAL,
	PRIMARY KEY("id")
);

ALTER TABLE "item_pedido"
ADD FOREIGN KEY("produto_id") REFERENCES "produto"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "item_pedido"
ADD FOREIGN KEY("pedido_id") REFERENCES "pedido"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;