CREATE TABLE "pedido" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"empresa_id" INTEGER NOT NULL,
	"data_compra" TIMESTAMP NOT NULL,
	"data_previsao" TIMESTAMP,
	"data_recebimento" TIMESTAMP,
	"cod_nota_fiscal"  VARCHAR(100),
	"descricao" VARCHAR(100),
	PRIMARY KEY("id")
);

ALTER TABLE "pedido"
ADD FOREIGN KEY("id") REFERENCES "item_pedido"("pedido_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;