CREATE TABLE "produto" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"empresa_id" INTEGER NOT NULL,
	"ingrediente_id" INTEGER NOT NULL,
	"unidade_medida_id" INTEGER NOT NULL,
	"nome" VARCHAR(100) NOT NULL,
	"codigo_ean" VARCHAR(200),
	"quantidade" INTEGER NOT NULL,
	"descricao" VARCHAR(200),
	"marca" VARCHAR(100),
	"validade" DATE,
	PRIMARY KEY("id")
);

ALTER TABLE "produto"
ADD FOREIGN KEY("unidade_medida_id") REFERENCES "unidade_medida"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "produto"
ADD FOREIGN KEY("empresa_id") REFERENCES "empresa"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "produto"
ADD FOREIGN KEY ("ingrediente_id") REFERENCES "ingrediente"(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;