CREATE TABLE "tarefa" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"empresa_id" INTEGER NOT NULL,
	"tipo_tarefa_id" INTEGER,
	"ingrediente_id" INTEGER,
	"relator_id" INTEGER,
	"responsavel_id" INTEGER NOT NULL,
	"pedido_id" INTEGER,
	"situacao" VARCHAR(255) NOT NULL,
	"quantidade_esperada" INTEGER,
	"contagem" INTEGER,
	"data_criacao" TIMESTAMP NOT NULL,
	"data_limite" TIMESTAMP,
	"data_conclusao" TIMESTAMP,
	PRIMARY KEY("id")
);

ALTER TABLE "tarefa"
ADD FOREIGN KEY("responsavel_id") REFERENCES "funcionario"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tarefa"
ADD FOREIGN KEY("relator_id") REFERENCES "funcionario"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tarefa"
ADD FOREIGN KEY("tipo_tarefa_id") REFERENCES "tipo_tarefa"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tarefa"
ADD FOREIGN KEY("ingrediente_id") REFERENCES "ingrediente"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tarefa"
ADD FOREIGN KEY("empresa_id") REFERENCES "empresa"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "tarefa"
ADD FOREIGN KEY("pedido_id") REFERENCES "pedido"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;